### ISSUE TITLE
DataError at /admin/scheduler/repeatablejob/add/ Invalid input of type: 'NoneType'. Convert to a byte, string or number first.

### ISSUE THREAD

**Issue by jpescalona** [istrategylabs/django-rq-scheduler#32]
Step to reproduce:
- Dependencies installed
```acme==0.26.1
alabaster==0.7.12
asn1crypto==0.24.0
Babel==2.6.0
backcall==0.1.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
coreapi==2.3.3
coreschema==0.0.4
croniter==0.3.26
cryptography==2.4.2
dateparser==0.7.0
decorator==4.3.0
decrypterlib==1.3
defusedxml==0.5.0
Django==2.0.6
django-auth-ldap==1.7.0
django-cors-headers==2.4.0
django-extensions==2.1.4
django-filter==2.0.0
django-jsonview==1.2.0
django-model-utils==3.1.2
django-mysql==2.4.1
django-redis==4.10.0
django-redis-cache==1.8.1
django-rq==1.3.0
django-rq-scheduler==1.1.1
django-watchman==0.15.0
djangorestframework==3.9.0
dnspython==1.16.0
docutils==0.14
drf-dynamic-fields==0.3.0
drf-extensions==0.4.0
idna==2.8
imagesize==1.1.0
ipython==7.2.0
ipython-genutils==0.2.0
itypes==1.1.0
jedi==0.13.2
Jinja2==2.10
jira==2.0.0
josepy==1.1.0
jprops==2.0.2
Markdown==3.0.1
MarkupSafe==1.1.0
mock==2.0.0
mysqlclient==1.3.14
oauthlib==3.0.0
packaging==18.0
parso==0.3.1
pbr==5.1.1
pem==18.2.0
pexpect==4.6.0
pickleshare==0.7.5
prompt-toolkit==2.0.7
ptyprocess==0.6.0
pyasn1==0.4.5
pyasn1-modules==0.2.3
pycparser==2.19
pycrypto==2.6.1
Pygments==2.3.1
PyJWT==1.7.1
pyOpenSSL==18.0.0
pyparsing==2.3.1
pyRFC3339==1.1
PySocks==1.6.8
python-dateutil==2.7.5
python-icinga2api==0.3.1
python-ldap==3.1.0
python-memcached==1.59
pytz==2018.9
redis==3.2.0
regex==2018.11.22
requests==2.21.0
requests-oauthlib==1.1.0
requests-toolbelt==0.8.0
rq==0.13.0
rq-scheduler==0.9
six==1.12.0
snowballstemmer==1.2.1
Sphinx==1.8.3
sphinxcontrib-websupport==1.1.0
suds-py3==1.3.3.0
traitlets==4.3.2
tzlocal==1.5.1
uritemplate==3.0.0
urllib3==1.24.1
uWSGI==2.0.17.1
wcwidth==0.1.7
```
- Create a new Scheduled or Repeatable job filling all the required data

Current behavior:
- A Django exception is thrown adding a new scheduled or repeatable job
```
Internal Server Error: /admin/scheduler/repeatablejob/add/
Traceback (most recent call last):
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/contrib/admin/options.py", line 575, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1554, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1451, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1491, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1027, in save_model
    obj.save()
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/scheduler/models.py", line 77, in save
    self.unschedule()
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/scheduler/models.py", line 104, in unschedule
    if self.is_scheduled():
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/scheduler/models.py", line 72, in is_scheduled
    return self.job_id in self.scheduler()
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/rq_scheduler/scheduler.py", line 260, in __contains__
    return self.connection.zscore(self.scheduled_jobs_key, job_id) is not None
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/redis/client.py", line 2593, in zscore
    return self.execute_command('ZSCORE', name, value)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/redis/client.py", line 774, in execute_command
    connection.send_command(*args)
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/redis/connection.py", line 663, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/redis/connection.py", line 125, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a byte, string or number first.
"POST /admin/scheduler/repeatablejob/add/ HTTP/1.1" 500 181002
```
Expected behavior: The scheduled/repeatable job is created

-----------------

I've been checking the value of job_id was None when calling to __contains__ function and this could potentially the reason of the failure:
```
  File "/home/jescalona/virtualenvs/bighaiku/lib/python3.7/site-packages/rq_scheduler/scheduler.py", line 260, in __contains__
    return self.connection.zscore(self.scheduled_jobs_key, job_id) is not None
```
Will investigate more and open a PR if i find the solution. Thanks

**Comment by pixelead0** [comment]
I have the same problem.

**Comment by pixelead0** [comment]
@chrisjun1 @CorneliusIV  @jcarbaugh @marissa-halpert @scottpdo 
Please merge this PR.

**Comment by alexandrukis** [comment]
Just here to confirm updating to 1.1.3 fixed this for me.

**Comment by jpescalona** [comment]
Hey! Yeah, this latest version 1.1.3 includes my changes and solved the issue. thanks
